apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000   # Specify the desired NodePort value
  selector:
    app: my-spring-app
